# Generated by Django 5.2.16 on 2026-07-29 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Time when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when this record was last updated.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Author's display name.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Time when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when this record was last updated.",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title shared by publication variants.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Time when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when this record was last updated.",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Published title of the book.", max_length=255
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Optional plain-text book summary."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Publication time, or null for unpublished books.",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured publishing metadata.",
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(
                        default=0, help_text="Number of pages in the book."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the book is active in the catalog.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Author who wrote the book.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        related_query_name="book",
                        to="myapp.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Time when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when this record was last updated.",
                    ),
                ),
                ("name", models.CharField(help_text="Node label.", max_length=200)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent node.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.node",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Time when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when this record was last updated.",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Public name shown for the profile.", max_length=200
                    ),
                ),
                (
                    "author",
                    models.OneToOneField(
                        help_text="Author represented by this profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        related_query_name="profile",
                        to="myapp.author",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecialEdition",
            fields=[
                (
                    "publication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="myapp.publication",
                    ),
                ),
                (
                    "edition_number",
                    models.IntegerField(
                        help_text="Number identifying this special edition."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("myapp.publication",),
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Time when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when this record was last updated.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique store name.", max_length=200, unique=True
                    ),
                ),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Books stocked by this store.",
                        to="myapp.book",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["author", "published_at"], name="book_author_pub_idx"
            ),
        ),
    ]
